// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

// List Layout
export const GET_ENTITY_DATA_SUCCESS = 'GET_ENTITY_DATA_SUCCESS';

// User Actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Engineers
export const GET_ENGINEERS_SUCCESS = 'GET_ENGINEERS_SUCCESS';
export const GET_ENGINEER_SUCCESS = 'GET_ENGINEER_SUCCESS';
export const GET_ENGINEER_FAILURE = 'GET_ENGINEER_FAILURE';

// Hours
export const GET_HOURS_SUCCESS = 'GET_HOURS_SUCCESS';
export const GET_HOUR_SUCCESS = 'GET_HOUR_SUCCESS';
export const ADD_HOUR_SUCCESS = 'ADD_HOUR_SUCCESS';
export const EDIT_HOUR_SUCCESS = 'EDIT_HOUR_SUCCESS';
export const DELETE_HOUR_SUCCESS = 'DELETE_HOUR_SUCCESS';

// Jobs
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOB_SUCCESS = 'GET_JOB_SUCCESS';
export const DELETE_JOBS_SUCCESS = 'DELETE_JOBS_SUCCESS';

// Skills
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS';
export const GET_SKILL_SUCCESS = 'SKILL_PROFILE_SUCCESS';
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
export const EDIT_SKILL_SUCCESS = 'EDIT_SKILL_SUCCESS';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';